notifications:
  email: false
language: clojure
before_script:
  - npm install -g npm@latest
#  - npm install phantomjs-prebuilt
#  - npm install jslint
  - npm -v
  - phantomjs -v
#after_script:
#  - lein figwheel&
#  - FIGHWEEL_SERVER_PID=$!
#  - sleep 60
#  - phantomjs scenarios.js
#  - kill -9 $FIGWHEEL_SERVER_PID
#  - jslint '*.js' || true
