notifications:
  email: false
language: clojure
before_script:
  - npm install -g npm@latest
  - npm install phantomjs-prebuilt@latest
  - npm install jslint
script:
  - lein test
  - lein figwheel &
  - FIGHWEEL_SERVER_PID=$!
  - echo $FIGHWEEL_SERVER_PID
  # Need some way to trigger phantomjs script when lein is done loading
  # instead of this arbitrary sleep period
  - sleep 60
  - ./node_modules/phantomjs-prebuilt/bin/phantomjs scenarios.js
  - kill -9 $FIGHWEEL_SERVER_PID
  - jslint '*.js' || true
